export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_RECIPE = "ADD_RECIPE";
export const ADD_RECIPE_FAIL = "ADD_RECIPE_FAIL";

export const GET_RECIPES = "GET_RECIPES";
export const GET_RECIPES_FAIL = "GET_RECIPES_FAIL";

export const GET_ITEM_RECIPE = "GET_ITEM_RECIPE";
export const GET_ITEM_RECIPE_FAIL = "GET_ITEM_RECIPE_FAIL";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const GET_MY_RECIPES = "GET_MY_RECIPES";
export const GET_MY_RECIPES_FAIL = "GET_MY_RECIPES_FAIL";

export const CHANGE_MY_PERSONAL_DATA = "CHANGE_MY_PERSONAL_DATA";
export const CHANGE_MY_PERSONAL_DATA_FAIL = "CHANGE_MY_PERSONAL_DATA_FAIL";

export const GET_MY_DATA = "GET_MY_DATA";
export const GET_MY_DATA_FAIL = "GET_MY_DATA_FAIL";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL";

export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const ADD_TO_FAVOURITE_FAIL = "ADD_TO_FAVOURITE_FAIL";

export const ADD_TO_FRIENDS = "ADD_TO_FRIENDS";
export const ADD_TO_FRIENDS_FAIL = "ADD_TO_FRIENDS_FAIL";

export const GET_FAVOURITE_RECIPES = "GET_FAVOURITE_RECIPES";
export const GET_FAVOURITE_RECIPES_FAIL = "GET_FAVOURITE_RECIPES_FAIL";



